import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.automationexercise.com/test_cases');
  await page.getByRole('link', { name: 'Test Case 1: Register User' }).click();
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await page.getByPlaceholder('Name').click();
  await page.getByPlaceholder('Name').fill('Aaroniya A');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.getByLabel('Mrs.').check();
  await page.getByLabel('Password *').click();
  await page.getByLabel('Password *').fill('aaroniyaarulraj');
  await page.locator('#days').selectOption('15');
  await page.locator('#months').selectOption('2');
  await page.locator('#years').selectOption('1991');
  await page.locator('#form form div').filter({ hasText: 'Sign up for our newsletter!' }).click();
  await page.getByLabel('Receive special offers from').check();
  await page.getByLabel('First name *').click();
  await page.getByLabel('First name *').fill('a');
  await page.getByLabel('Last name *').click();
  await page.getByLabel('Last name *').fill('A');
  await page.getByLabel('Company', { exact: true }).click();
  await page.getByLabel('Company', { exact: true }).fill('A');
  await page.getByLabel('Address * (Street address, P.').click();
  await page.getByLabel('Address * (Street address, P.').fill('a');
  await page.getByLabel('Address 2').click();
  await page.getByLabel('Address 2').fill('m');
  await page.getByLabel('State *').click();
  await page.getByLabel('State *').fill('tamilnadu');
  await page.getByLabel('City *').click();
  await page.getByLabel('State *').click();
  await page.getByLabel('State *').fill('Tamilnadu');
  await page.getByLabel('City *').click();
  await page.getByLabel('City *').fill('D');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('6');
  await page.getByLabel('Mobile Number *').click();
  await page.getByLabel('Mobile Number *').fill('9976287490');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.getByRole('link', { name: ' Delete Account' }).click();
  await page.getByRole('link', { name: 'Continue' }).click();
});